import com.google.api.services.drive.Drive;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'zo43' at '18/08/16 13:45' with Gradle 2.12
 *
 * @author zo43, @date 18/08/16 13:45
 */
public class LibraryTest {

    private static final Logger logger = LoggerFactory.getLogger(LibraryTest.class);

    @Test
    public void testSomeLibraryMethod() throws Exception {
        Drive driveService = Library.getDriveService();
        Drive.Files.List list = driveService.files().list();
        for (String file : list.keySet()) {
            logger.info(file);

        }
    }
}
